name: Deploy static site to Azure Web App - reverse-breakout

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66A972BC5F0541859DF88583086C2CA0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1A5F1CE00E74ACBB3DF66DF744BB633 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27DC335338FE4800864FE1E54CC48548 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reverse-breakout'
          slot-name: 'Production'
          package: .
